
eureka:
  instance:
    hostname: gateway-spring-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka/

server:
  port: 7001

spring:
  application:
    name: gateway-spring-gateway
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 # 采样率 0 - 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: product-ms # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #          uri: http://localhost:8002
          uri: lb://product-ms
          predicates:
            # - Path=/payment/get/** # 断言，路径相匹配的进行路由
            # - Path=/product/timeout/get/** # 断言，路径相匹配的进行路由
            - Path=/product/*

        #        - id: payment_route3 # 路由的id,没有规定规则但要求唯一,建议配合服务名
        #            #匹配后提供服务的路由地址
        #          uri: http://localhost:8002
        #          #          uri: lb://cloud-payment-service
        #          predicates:
        #            #            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        #            - Path=/customer/circuit/get/** # 断言，路径相匹配的进行路由

        - id: order-ms
          #          uri: http://localhost:8002
          uri: lb://order-ms
          predicates:
            - Path=/order/** #断言,路径相匹配的进行路由
          # - After=2020-06-06T16:05:00.064+08:00[Asia/Shanghai] # 时间之后 生效
          #            - Cookie=username,mizhicn   #带Cookie，并且username的值为mizhicn
          #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
        - id: pay-ms
          uri: lb://pay-ms
          predicates:
            - Path=/pay/** #断言,路径相匹配的进行路由
